# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'assets/images/uploads'

collections:
  - name: 'media'
    label: 'Media'
    folder: '_media/'
    slug: "{{slug}}"
    preview_path: "{{permalink}}"
    fields:
      - { label: "Title", name: title, widget: string }
      - { label: "Layout", name: layout, widget: hidden, default: "single-layout" }
      - { label: "Categories", name: "categories", widget: "select", options: ["standard", "featured"], default: "standard"}
      - { label: "Featured Image", name: "featured-image", widget: "image", required: false}
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: true }
      - { label: "Body", name: body, widget: markdown }