# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

display_url: https://budgetjusticesa.org
logo_url: https://budgetjusticesa.org/assets/svg/logo.svg

media_folder: 'assets/images/uploads'

collections:
  - name: 'media'
    label: 'Media item'
    folder: '_media/'
    create: true
    slug: "{{slug}}"
    preview_path: '_media/{{slug}}'
    fields:
      - { label: "Title", name: title, widget: string }
      - { label: "Layout", name: layout, widget: hidden, default: "single-post" }
      - { label: "Categories", name: "categories", widget: "select", options: ["standard", "featured"], default: "standard"}
      - { label: "Featured Image", name: "featured-image", widget: "image", required: false}
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: true }
      - { label: "Body", name: body, widget: markdown }

  - name: "pages"
    label: "Pages"
    files:
      # Advocacy
      - name: "advocay"
        label: "Advocacy page"
        delete: false
        file: "advocacy.md"
        slug: "{{slug}}"
        create: false
        fields:
          - name: uploads
            label: "Documents"
            label_singular: "Document"
            widget: list
            fields:
              - { label: "Document name", name: "documentname", widget: "string" }
              - { label: "Document", name: "link", widget: "file" }