backend:
  name: git-gateway
  branch: master
  repo: justinslack/bjc-uat
  base_url: https://api.netlify.com
  accept_roles:
    - admin
    - editor

site_url: https://budgetjusticesa.org

publish_mode: editorial_workflow

media_folder: "assets/images/uploads"

collections:
  - name: "media" # Used in routes, e.g., /admin/collections/blog
    label: "Media" # Used in the UI
    folder: "_media" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "single-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}